### ISSUE TITLE
Implement garbage collection in secondary regions 

### ISSUE THREAD

**Issue by lynnliu030** [skyplane-project/skystore#41]
The pull-based get-object mechanism can create lots of copies in different regions, and some of them might be never reused again, this leads to high storage cost. 

We need to implement garbage collection mechanism and perform periodic cleanup in those secondary region object stores. One policy of doing this is to just use TTL, another way is to do cache eviction, i.e. via policies like LRU. 

One way to do it is 
1) S3Proxy maintains separate service that periodically probes SkyStore server to ask for list of objects to delete
2) SkyStore server maintains metadata (i.e. live time, last accessed) for each PhysicalObjectLocator, it implements a `cleanup` API call to scan those needed to be evicted, return `List[PhysicalObjectLocator]`
2) Dataplane performs delete_objects accordingly

Any other ways to make it more efficient? @simon-mo @sarahwooders

**Comment by simon-mo** [comment]
Some non-binding ideas... 

I think it's okay to leave TTL unimplemented for now. In the future, I
see the proper way is either through Object Lifecycle and TTL
management:

https://aws.amazon.com/blogs/aws/amazon-s3-object-expiration/
https://learn.microsoft.com/en-us/azure/storage/blobs/lifecycle-
management-overview?tabs=azure-portal
https://cloud.google.com/storage/docs/lifecycle

Or some sort of metadata tags on the objects so the proxy can
periodically clean. 

I think we should avoid storing the ground truth TTL information in the
cloud plane because it is too fine-grained, and in case the control
plane is down/overloaded, deletion functionality can be performed
another way.
